document:
  name: Linee Guida Indice nazionale dei domicili digitali delle persone fisiche
  description:
      Linee Guida Indice nazionale dei domicili digitali delle persone fisiche
  tags:
    - domicilio digitale
    - linee guida